### ISSUE TITLE
spark-bigquery support in pyspark?

### ISSUE THREAD

**Issue by BogdanCojocar** [spotify/spark-bigquery#21]
I'm trying to use the spark-biguery connector using the pyspark shell using `pyspark --package com.spotify:spark-bigquery_2.10:0.1.0 `. When I'm trying to import the main package  `import com.spotify.spark.bigquery` I get an `ImportError` Is there no way to use this connector in python?

**Comment by mkanchwala** [comment]
Is this resolved or what?
