### ISSUE TITLE
Suggested replacements to this project?

### ISSUE THREAD

**Issue by alexklibisz** [spotify/spark-bigquery#66]
The README suggests that this project is no longer used widely within Spotify. Are there suggested replacements for transferring data from Bigquery into spark for big processing jobs? Or is this workflow in general outdated? So far this is the best piece of OSS I've found for the purpose.

**Comment by pkallos** [comment]
@GoogleCloudPlatform recently released [GoogleCloudPlatform/spark-bigquery-connector](https://github.com/GoogleCloudPlatform/spark-bigquery-connector) with read support, assume write support is in the works with GoogleCloudPlatform/spark-bigquery-connector#7

**Comment by alexklibisz** [comment]
Thanks for following up. That is pretty recent and from scanning the readme seems to do what I need.
